<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.*-*" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.*-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIManHua.ServiceDefaults\AIManHua.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AIManHua.Domain\AIManHua.Domain.csproj" />
    <ProjectReference Include="..\AIManHua.Infrastructure\AIManHua.Infrastructure.csproj" />
  </ItemGroup>

</Project>
